node{
def commit_id
stage('setup'){
    checkout scm //clone this repo in jenkins
    sh 'git rev-parse --short HEAD > .git/commit_id' // Fetching the commit id and then put that ifd in to .git/commit_id file
    commit_id = readFile('.git/commit_id').trim()  //trim to rmeove spaces and return a string character
}


stage('test'){
    nodejs(nodeJSInstallationName: 'Nodejs'){
    dir("App") {
    sh "pwd"

    sh 'npm install --donly-dev'
    sh 'npm test'
    }
}
}

stage('docker build/push'){
    dir("App") {
    docker.withRegistry('https://index.docker.io/', 'dockerhub') {
       def app = docker.build("amanpreet9391/simple-nodejs-app:${commit_id}", '.').push()
     }
    }
   
}








}